version: '3.8'

services:
  lavalink:
    image: fredboat/lavalink:4.0.1
    container_name: lavalink
    restart: unless-stopped
    ports:
      - "2333:2333"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./logs:/opt/Lavalink/logs
    environment:
      - JAVA_OPTS=-Xmx2G
    networks:
      - lavalink

networks:
  lavalink:
    driver: bridge
